// Translated content overlays per country per language
// Structure: LANG_CONTENT[country][lang] = { timeline, steps, faq, checklist }
// Only non-English translations stored here. English uses countries-data.js directly.
const LANG_CONTENT = {
  us: {
    es: {
      timeline: [
        { phase: '12–18 Meses Antes', title: 'Temporada de Primarias', desc: 'Los candidatos se presentan, se celebran primarias y asambleas en todos los estados.' },
        { phase: '6–4 Meses Antes', title: 'Convenciones Nacionales', desc: 'Los partidos nominan formalmente a los candidatos presidenciales y vicepresidenciales.' },
        { phase: '4–1 Meses Antes', title: 'Temporada de Campaña', desc: 'Debates presidenciales, mítines, anuncios de TV y campaña en estados clave.' },
        { phase: '45 Días Antes', title: 'Fecha Límite de Registro', desc: 'La mayoría de los estados requieren registro 15–30 días antes del Día de Elección.' },
        { phase: '2–4 Semanas Antes', title: 'Votación Anticipada', desc: 'Muchos estados ofrecen votación anticipada en persona y por correo.' },
        { phase: 'Primer Martes después del 1 de Nov', title: 'Día de Elección', desc: 'Las urnas abren en todo el país. Vote en su lugar de votación asignado.' },
        { phase: 'Dic–Ene', title: 'Colegio Electoral e Inauguración', desc: 'Los electores votan en diciembre. El presidente toma posesión el 20 de enero.' },
      ],
      steps: [
        { num: 1, icon: '📝', title: 'Registro de Votantes', summary: 'Regístrese en línea, por correo o en persona antes de la fecha límite.',
          details: `<ul><li><strong>¿Quién puede registrarse?</strong> Ciudadanos estadounidenses mayores de 18 años que cumplan con los requisitos de residencia del estado.</li><li><strong>Cómo:</strong> En línea en vote.gov, por correo, en el DMV o el mismo día en algunos estados.</li><li><strong>Qué necesita:</strong> Número de seguro social o licencia de conducir, comprobante de domicilio.</li></ul><div class="alert alert-important">⚠️ Las fechas límite varían según el estado; algunos permiten el registro el mismo día, otros requieren 30 días.</div>` },
        { num: 2, icon: '🏛️', title: 'Primarias y Asambleas', summary: 'Los partidos seleccionan a sus candidatos a través de elecciones a nivel estatal.',
          details: `<ul><li><strong>Primarias Abiertas</strong> — Cualquier votante registrado puede participar.</li><li><strong>Primarias Cerradas</strong> — Solo los miembros registrados del partido pueden votar.</li><li><strong>Asambleas (Caucuses)</strong> — Reuniones locales donde los votantes apoyan públicamente a los candidatos.</li><li><strong>Delegados</strong> — Los ganadores ganan delegados para la nominación del partido.</li></ul><div class="alert alert-tip">💡 Verifique si su estado tiene primarias abiertas o cerradas; es posible que deba registrarse en un partido.</div>` },
        { num: 3, icon: '📢', title: 'Temporada de Campaña', summary: 'Siga los debates, mítines y la cobertura de los medios.',
          details: `<ul><li>🎤 <strong>Debates Presidenciales</strong> — Organizados por la Comisión de Debates Presidenciales.</li><li>📺 <strong>Anuncios de TV y Digitales</strong> — Miles de millones gastados en publicidad.</li><li>🗺️ <strong>Estados Indecisos</strong> — Los candidatos se enfocan en estados clave altamente competitivos.</li><li>💰 <strong>Financiamiento de Campaña</strong> — Regulado por la FEC con la participación de PACs y Super PACs.</li></ul><div class="alert alert-warning">⚠️ Verifique las afirmaciones en FactCheck.org o PolitiFact antes de compartirlas.</div>` },
        { num: 4, icon: '🗳️', title: 'Emitir su Voto', summary: 'Vote en persona, por adelantado o por correo.',
          details: `<h4 style="margin-bottom:0.5rem;color:#e2e8f0">Votación en Persona</h4><ul><li>Encuentre su lugar de votación en vote.org/polling-place-locator.</li><li>Lleve la identificación requerida (varía según el estado).</li><li>Use una boleta de papel o una máquina de votación electrónica.</li></ul><h4 style="margin:1rem 0 0.5rem;color:#e2e8f0">Por Correo / Ausente</h4><ul><li>Solicite una boleta a la oficina electoral de su estado.</li><li>Algunos estados (OR, WA, CO) votan completamente por correo.</li></ul><div class="alert alert-caution">🚨 Las boletas por correo deben tener el sello postal del Día de la Elección en la mayoría de los estados.</div>` },
        { num: 5, icon: '📊', title: 'Conteo y Colegio Electoral', summary: 'Los votos populares determinan los electores estatales.',
          details: `<ul><li><strong>Voto Popular</strong> — Cada estado cuenta los votos; el ganador se lleva la mayoría/todos los electores.</li><li><strong>Colegio Electoral</strong> — 538 electores en total; se necesitan 270 para ganar.</li><li><strong>Estados Indecisos</strong> — Las contiendas cerradas en estados clave deciden la elección.</li><li><strong>Certificación</strong> — El Congreso certifica los votos electorales en enero.</li></ul>` },
        { num: 6, icon: '🏁', title: 'Inauguración', summary: 'El presidente electo asume el cargo el 20 de enero.',
          details: `<ul><li><strong>Transición</strong> — ~75 días entre la elección y la inauguración.</li><li><strong>Juramento del Cargo</strong> — Toma de juramento en el Capitolio de EE. UU.</li><li><strong>Recuentos</strong> — Se desencadenan si los márgenes son muy estrechos (varía según el estado).</li><li><strong>Desafíos Legales</strong> — Los resultados pueden ser impugnados en los tribunales.</li></ul>` },
      ],
      faq: [
        { q: '¿Qué es el Colegio Electoral?', a: 'Un sistema de 538 electores que eligen formalmente al presidente. Cada estado tiene electores iguales a su representación en el Congreso. Un candidato necesita 270 para ganar.' },
        { q: '¿Necesito identificación para votar?', a: 'Depende de su estado. Algunos requieren identificación con foto, otros aceptan identificación sin foto, y algunos no tienen requisito estricto. Consulte vote.org para su estado.' },
        { q: '¿Puedo votar si me mudé recientemente?', a: 'Necesita actualizar su registro a su nueva dirección. Algunos estados ofrecen registro el mismo día. Consulte con la oficina electoral de su nuevo estado.' },
        { q: '¿Qué son los estados indecisos?', a: 'Estados donde ningún partido tiene una mayoría fuerte, lo que los hace altamente competitivos. Ejemplos incluyen Pensilvania, Míchigan, Wisconsin, Arizona y Georgia.' },
        { q: '¿Cuál es la diferencia entre primarias y la elección general?', a: 'Las primarias permiten a los miembros del partido elegir a su candidato. La elección general es cuando todos los votantes eligen entre los nominados de los partidos para el cargo.' },
      ],
      checklist: ['Registrarse para votar (verifique la fecha límite de su estado)', 'Verificar su lugar de votación', 'Reunir la identificación requerida para su estado', 'Investigar candidatos y medidas electorales', 'Anotar fechas clave: primaria, fecha límite de registro, Día de Elección', 'Elegir método de votación: en persona, anticipada o por correo', '¡Emitir su voto!'],
    },
  },
  in: {
    hi: {
      timeline: [
        { phase: '6–12 महीने पहले', title: 'चुनाव-पूर्व', desc: 'राजनीतिक दल घोषणापत्र तैयार करते हैं, गठबंधन बनाते हैं और उम्मीदवारों का चयन करते हैं।' },
        { phase: '2–3 महीने पहले', title: 'चुनाव घोषणा', desc: 'भारत निर्वाचन आयोग (ECI) तारीखों की घोषणा करता है और आदर्श आचार संहिता लागू होती है।' },
        { phase: '1–2 महीने पहले', title: 'प्रचार अभियान', desc: 'रैलियाँ, रोड शो और मीडिया अभियान सभी निर्वाचन क्षेत्रों में।' },
        { phase: 'अंतिम तिथि से पहले', title: 'मतदाता सूची सत्यापन', desc: 'nvsp.in पर अपना नाम मतदाता सूची में जाँचें।' },
        { phase: 'कई चरणों में', title: 'मतदान दिवस', desc: 'भारत में 4–6 सप्ताह में कई चरणों में ईवीएम से मतदान होता है।' },
        { phase: 'अंतिम चरण के बाद', title: 'मतगणना और परिणाम', desc: 'सभी मतों की एक साथ गिनती। उसी दिन परिणाम घोषित।' },
      ],
      steps: [
        { num: 1, icon: '📝', title: 'मतदाता सूची पंजीकरण', summary: 'EPIC कार्ड के साथ मतदाता सूची में अपना नाम दर्ज कराएँ।',
          details: `<ul><li><strong>पात्रता:</strong> भारतीय नागरिक, 18+ वर्ष, निर्वाचन क्षेत्र का निवासी।</li><li><strong>कैसे:</strong> nvsp.in पर ऑनलाइन या वोटर हेल्पलाइन ऐप (फॉर्म 6) से आवेदन करें।</li><li><strong>EPIC कार्ड:</strong> इलेक्टर्स फोटो आइडेंटिटी कार्ड — आपका प्राथमिक मतदाता पहचान पत्र।</li><li><strong>आवश्यक:</strong> आधार, आयु प्रमाण, पासपोर्ट साइज़ फोटो, पता प्रमाण।</li></ul><div class="alert alert-important">⚠️ हर चुनाव से पहले मतदाता सूची जाँचें — संशोधन के दौरान नाम हटाए जा सकते हैं।</div>` },
        { num: 2, icon: '🏛️', title: 'उम्मीदवार और पार्टियाँ', summary: 'राष्ट्रीय और क्षेत्रीय पार्टी उम्मीदवारों के बारे में जानें।',
          details: `<ul><li><strong>राष्ट्रीय पार्टियाँ</strong> — BJP, INC, और अन्य ECI द्वारा मान्यता प्राप्त।</li><li><strong>क्षेत्रीय पार्टियाँ</strong> — राज्य-स्तरीय पार्टियाँ जैसे AAP, TMC, DMK, आदि।</li><li><strong>निर्दलीय उम्मीदवार</strong> — जमानत राशि के साथ नामांकन दाखिल कर सकते हैं।</li><li><strong>शपथ पत्र</strong> — उम्मीदवारों को संपत्ति, आपराधिक मामले और शिक्षा घोषित करनी होती है।</li></ul><div class="alert alert-tip">💡 पारदर्शिता के लिए ECI वेबसाइट या MyNeta.info पर उम्मीदवार शपथ पत्र देखें।</div>` },
        { num: 3, icon: '📢', title: 'प्रचार अभियान', summary: 'MCC के तहत रैलियाँ, रोड शो और मीडिया अभियान।',
          details: `<ul><li>🎤 <strong>जनसभाएँ</strong> — पार्टी नेताओं द्वारा संबोधित बड़ी सभाएँ।</li><li>🚗 <strong>रोड शो</strong> — उम्मीदवार निर्वाचन क्षेत्रों में परेड करते हैं।</li><li>📱 <strong>सोशल मीडिया</strong> — प्रचार और संदेश के लिए व्यापक उपयोग।</li><li>📜 <strong>आदर्श आचार संहिता</strong> — ECI द्वारा लागू प्रचार पर सख्त नियम।</li></ul><div class="alert alert-warning">⚠️ प्रत्येक चरण में मतदान दिवस से 48 घंटे पहले प्रचार बंद होना चाहिए।</div>` },
        { num: 4, icon: '🗳️', title: 'अपना मत डालें', summary: 'इलेक्ट्रॉनिक वोटिंग मशीन (EVM) से मतदान करें।',
          details: `<ul><li>वोटर हेल्पलाइन ऐप या nvsp.in पर अपना मतदान केंद्र खोजें।</li><li>अपना EPIC कार्ड या स्वीकृत फोटो ID (आधार, पासपोर्ट, आदि) लाएँ।</li><li>दोहरे मतदान को रोकने के लिए आपकी उंगली पर अमिट स्याही लगाई जाती है।</li><li>अपने उम्मीदवार के बगल में <strong>EVM</strong> पर बटन दबाएँ।</li><li><strong>VVPAT</strong> (पेपर ट्रेल स्लिप) पर अपना वोट सत्यापित करें।</li></ul><div class="alert alert-caution">🚨 मतदान आमतौर पर सुबह 7 बजे से शाम 6 बजे तक होता है। लंबी कतारों से बचने के लिए जल्दी पहुँचें।</div>` },
        { num: 5, icon: '📊', title: 'मतगणना और परिणाम', summary: 'एक निर्धारित दिन सभी EVM की गिनती एक साथ होती है।',
          details: `<ul><li><strong>मतगणना दिवस</strong> — सभी चरणों की गिनती एक साथ मतगणना केंद्रों पर।</li><li><strong>EVM मतगणना</strong> — सख्त निगरानी में इलेक्ट्रॉनिक मशीनों की गिनती।</li><li><strong>VVPAT सत्यापन</strong> — यादृच्छिक VVPAT पर्चियों का EVM परिणामों से मिलान।</li><li><strong>परिणाम</strong> — उसी दिन घोषित; 272+ लोक सभा सीटों वाला दल/गठबंधन सरकार बनाता है।</li></ul>` },
        { num: 6, icon: '🏁', title: 'सरकार गठन', summary: 'बहुमत दल/गठबंधन सरकार बनाता है।',
          details: `<ul><li><strong>बहुमत</strong> — 543 सदस्यीय लोक सभा में 272 सीटें आवश्यक।</li><li><strong>प्रधानमंत्री चयन</strong> — बहुमत दल/गठबंधन का नेता प्रधानमंत्री बनता है।</li><li><strong>गठबंधन</strong> — किसी एक दल को बहुमत न मिलने पर गठबंधन बनता है।</li><li><strong>शपथ ग्रहण</strong> — राष्ट्रपति द्वारा PM और मंत्रिपरिषद को शपथ दिलाई जाती है।</li></ul>` },
      ],
      faq: [
        { q: 'ईवीएम और वीवीपैट क्या है?', a: 'ईवीएम (इलेक्ट्रॉनिक वोटिंग मशीन) का उपयोग इलेक्ट्रॉनिक रूप से वोट डालने के लिए किया जाता है। वीवीपैट (वोटर वेरिफ़ाइबल पेपर ऑडिट ट्रेल) एक कागज़ी पर्ची प्रिंट करता है ताकि आप सत्यापित कर सकें कि आपका वोट सही दर्ज हुआ।' },
        { q: 'भारत में कई चरणों में मतदान क्यों होता है?', a: 'विशाल पैमाने (90 करोड़+ मतदाता) के कारण, चुनाव चरणों में होते हैं ताकि सुरक्षा बल और ECI अधिकारी पूरे देश में तैनात किए जा सकें।' },
        { q: 'आदर्श आचार संहिता क्या है?', a: 'ECI द्वारा जारी नियमों का एक सेट जो चुनाव के दौरान पार्टियों और उम्मीदवारों के व्यवहार को नियंत्रित करता है — कोई घृणा भाषण नहीं, राजनीतिक लाभ के लिए सरकारी घोषणाएँ नहीं, आदि।' },
        { q: 'क्या NRI भारतीय चुनावों में वोट कर सकते हैं?', a: 'हाँ, NRI विदेशी मतदाता के रूप में पंजीकृत होने पर वोट कर सकते हैं, लेकिन उन्हें मतदान केंद्र पर व्यक्तिगत रूप से उपस्थित होना होगा। डाक मतपत्र सुविधा का विस्तार किया जा रहा है।' },
        { q: 'मतदाता पहचान पत्र के रूप में कौन से दस्तावेज़ मान्य हैं?', a: 'EPIC कार्ड, आधार, पासपोर्ट, ड्राइविंग लाइसेंस, पैन कार्ड, या ECI द्वारा स्वीकृत कोई भी सरकारी फोटो पहचान पत्र।' },
      ],
      checklist: ['मतदाता सूची में अपना नाम सत्यापित करें (nvsp.in)', 'अपना EPIC कार्ड या स्वीकृत फोटो पहचान पत्र तैयार रखें', 'वोटर हेल्पलाइन ऐप पर अपना मतदान केंद्र खोजें', 'myneta.info पर उम्मीदवारों के बारे में जानें', 'अपने निर्वाचन क्षेत्र के मतदान चरण और तारीख जाँचें', 'ईवीएम से मतदान करें और वीवीपैट पर सत्यापित करें', 'eciresults.nic.in पर परिणाम देखें'],
    },
    kn: {
      timeline: [
        { phase: '6–12 ತಿಂಗಳ ಮೊದಲು', title: 'ಚುನಾವಣಾ ಪೂರ್ವ', desc: 'ರಾಜಕೀಯ ಪಕ್ಷಗಳು ಪ್ರಣಾಳಿಕೆಗಳನ್ನು ಸಿದ್ಧಪಡಿಸುತ್ತವೆ, ಮೈತ್ರಿಗಳನ್ನು ರಚಿಸುತ್ತವೆ ಮತ್ತು ಅಭ್ಯರ್ಥಿಗಳನ್ನು ಆಯ್ಕೆ ಮಾಡುತ್ತವೆ.' },
        { phase: '2–3 ತಿಂಗಳ ಮೊದಲು', title: 'ಚುನಾವಣಾ ಘೋಷಣೆ', desc: 'ಭಾರತೀಯ ಚುನಾವಣಾ ಆಯೋಗ (ECI) ದಿನಾಂಕಗಳನ್ನು ಘೋಷಿಸುತ್ತದೆ ಮತ್ತು ಮಾದರಿ ನೀತಿ ಸಂಹಿತೆ ಜಾರಿಗೆ ಬರುತ್ತದೆ.' },
        { phase: '1–2 ತಿಂಗಳ ಮೊದಲು', title: 'ಪ್ರಚಾರ ಅಭಿಯಾನ', desc: 'ಕ್ಷೇತ್ರಗಳಾದ್ಯಂತ ರ‍್ಯಾಲಿಗಳು, ರೋಡ್‌ಶೋಗಳು ಮತ್ತು ಮಾಧ್ಯಮ ಪ್ರಚಾರಗಳು.' },
        { phase: 'ಗಡುವಿನ ಮೊದಲು', title: 'ಮತದಾರರ ಪಟ್ಟಿ ಪರಿಶೀಲನೆ', desc: 'nvsp.in ನಲ್ಲಿ ಮತದಾರರ ಪಟ್ಟಿಯಲ್ಲಿ ನಿಮ್ಮ ಹೆಸರನ್ನು ಪರಿಶೀಲಿಸಿ.' },
        { phase: 'ಹಲವಾರು ಹಂತಗಳಲ್ಲಿ', title: 'ಮತದಾನದ ದಿನಗಳು', desc: 'ಭಾರತವು EVM ಗಳನ್ನು ಬಳಸಿ 4-6 ವಾರಗಳಲ್ಲಿ ಹಲವಾರು ಹಂತಗಳಲ್ಲಿ ಮತ ಚಲಾಯಿಸುತ್ತದೆ.' },
        { phase: 'ಅಂತಿಮ ಹಂತದ ನಂತರ', title: 'ಎಣಿಕೆ ದಿನ ಮತ್ತು ಫಲಿತಾಂಶಗಳು', desc: 'ಮತಗಳನ್ನು ಏಕಕಾಲದಲ್ಲಿ ಎಣಿಸಲಾಗುತ್ತದೆ. ಅದೇ ದಿನ ಫಲಿತಾಂಶಗಳನ್ನು ಘೋಷಿಸಲಾಗುತ್ತದೆ.' },
      ],
      steps: [
        { num: 1, icon: '📝', title: 'ಮತದಾರರ ಪಟ್ಟಿ ನೋಂದಣಿ', summary: 'EPIC ಕಾರ್ಡ್‌ನೊಂದಿಗೆ ಮತದಾರರ ಪಟ್ಟಿಯಲ್ಲಿ ನಿಮ್ಮ ಹೆಸರನ್ನು ಸೇರಿಸಿ.',
          details: `<ul><li><strong>ಅರ್ಹತೆ:</strong> ಭಾರತೀಯ ನಾಗರಿಕ, 18+ ವರ್ಷ, ಕ್ಷೇತ್ರದ ನಿವಾಸಿ.</li><li><strong>ಹೇಗೆ:</strong> nvsp.in ನಲ್ಲಿ ಆನ್‌ಲೈನ್‌ನಲ್ಲಿ ಅಥವಾ ವೋಟರ್ ಹೆಲ್ಪ್‌ಲೈನ್ ಅಪ್ಲಿಕೇಶನ್ (ಫಾರ್ಮ್ 6) ಮೂಲಕ ಅರ್ಜಿ ಸಲ್ಲಿಸಿ.</li><li><strong>EPIC ಕಾರ್ಡ್:</strong> ಎಲೆಕ್ಟರ್ಸ್ ಫೋಟೋ ಐಡೆಂಟಿಟಿ ಕಾರ್ಡ್ — ನಿಮ್ಮ ಪ್ರಾಥಮಿಕ ವೋಟರ್ ಐಡಿ.</li><li><strong>ಏನು ಬೇಕು:</strong> ಆಧಾರ್, ವಯಸ್ಸಿನ ಪುರಾವೆ, ಪಾಸ್‌ಪೋರ್ಟ್ ಅಳತೆಯ ಭಾವಚಿತ್ರ, ವಿಳಾಸ ಪುರಾವೆ.</li></ul><div class="alert alert-important">⚠️ ಪ್ರತಿ ಚುನಾವಣೆಯ ಮೊದಲು ಮತದಾರರ ಪಟ್ಟಿಯನ್ನು ಪರಿಶೀಲಿಸಿ — ಪರಿಷ್ಕರಣೆಗಳ ಸಮಯದಲ್ಲಿ ಹೆಸರುಗಳನ್ನು ತೆಗೆದುಹಾಕಬಹುದು.</div>` },
        { num: 2, icon: '🏛️', title: 'ಅಭ್ಯರ್ಥಿಗಳು ಮತ್ತು ಪಕ್ಷಗಳು', summary: 'ರಾಷ್ಟ್ರೀಯ ಮತ್ತು ಪ್ರಾದೇಶಿಕ ಪಕ್ಷದ ಅಭ್ಯರ್ಥಿಗಳ ಬಗ್ಗೆ ಸಂಶೋಧನೆ ಮಾಡಿ.',
          details: `<ul><li><strong>ರಾಷ್ಟ್ರೀಯ ಪಕ್ಷಗಳು</strong> — ECI ಯಿಂದ ಗುರುತಿಸಲ್ಪಟ್ಟ BJP, INC ಮತ್ತು ಇತರವು.</li><li><strong>ಪ್ರಾದೇಶಿಕ ಪಕ್ಷಗಳು</strong> — AAP, TMC, DMK ಮುಂತಾದ ರಾಜ್ಯಮಟ್ಟದ ಪಕ್ಷಗಳು.</li><li><strong>ಸ್ವತಂತ್ರ ಅಭ್ಯರ್ಥಿಗಳು</strong> — ಠೇವಣಿಯೊಂದಿಗೆ ನಾಮಪತ್ರ ಸಲ್ಲಿಸುವ ಮೂಲಕ ಸ್ಪರ್ಧಿಸಬಹುದು.</li><li><strong>ಅಫಿಡವಿಟ್‌ಗಳು</strong> — ಅಭ್ಯರ್ಥಿಗಳು ಆಸ್ತಿಗಳು, ಕ್ರಿಮಿನಲ್ ಪ್ರಕರಣಗಳು ಮತ್ತು ಶಿಕ್ಷಣವನ್ನು ಘೋಷಿಸಬೇಕು.</li></ul><div class="alert alert-tip">💡 ಪಾರದರ್ಶಕತೆಗಾಗಿ ECI ವೆಬ್‌ಸೈಟ್ ಅಥವಾ MyNeta.info ನಲ್ಲಿ ಅಭ್ಯರ್ಥಿಗಳ ಅಫಿಡವಿಟ್‌ಗಳನ್ನು ಪರಿಶೀಲಿಸಿ.</div>` },
        { num: 3, icon: '📢', title: 'ಪ್ರಚಾರ ಅಭಿಯಾನ', summary: 'MCC ಅಡಿಯಲ್ಲಿ ರ‍್ಯಾಲಿಗಳು, ರೋಡ್‌ಶೋಗಳು ಮತ್ತು ಮಾಧ್ಯಮ ಪ್ರಚಾರಗಳು.',
          details: `<ul><li>🎤 <strong>ಸಾರ್ವಜನಿಕ ರ‍್ಯಾಲಿಗಳು</strong> — ಪಕ್ಷದ ನಾಯಕರು ಉದ್ದೇಶಿಸಿ ಮಾತನಾಡುವ ದೊಡ್ಡ ಸಭೆಗಳು.</li><li>🚗 <strong>ರೋಡ್‌ಶೋಗಳು</strong> — ಕ್ಷೇತ್ರಗಳ ಮೂಲಕ ಅಭ್ಯರ್ಥಿಗಳ ಮೆರವಣಿಗೆ.</li><li>📱 <strong>ಸಾಮಾಜಿಕ ಮಾಧ್ಯಮ</strong> — ಪ್ರಚಾರ ಮತ್ತು ಸಂದೇಶ ರವಾನೆಗಾಗಿ ಹೆಚ್ಚು ಬಳಸಲಾಗುತ್ತದೆ.</li><li>📜 <strong>ಮಾದರಿ ನೀತಿ ಸಂಹಿತೆ</strong> — ECI ಜಾರಿಗೊಳಿಸಿದ ಪ್ರಚಾರದ ಕಟ್ಟುನಿಟ್ಟಾದ ನಿಯಮಗಳು.</li></ul><div class="alert alert-warning">⚠️ ಪ್ರತಿ ಹಂತದಲ್ಲಿ ಮತದಾನದ ದಿನದ 48 ಗಂಟೆಗಳ ಮೊದಲು ಪ್ರಚಾರವನ್ನು ನಿಲ್ಲಿಸಬೇಕು.</div>` },
        { num: 4, icon: '🗳️', title: 'ನಿಮ್ಮ ಮತದಾನ', summary: 'ಎಲೆಕ್ಟ್ರಾನಿಕ್ ವೋಟಿಂಗ್ ಯಂತ್ರಗಳನ್ನು (EVM ಗಳು) ಬಳಸಿ ಮತ ಚಲಾಯಿಸಿ.',
          details: `<ul><li>ವೋಟರ್ ಹೆಲ್ಪ್‌ಲೈನ್ ಅಪ್ಲಿಕೇಶನ್ ಅಥವಾ nvsp.in ನಲ್ಲಿ ನಿಮ್ಮ ಮತಗಟ್ಟೆಯನ್ನು ಹುಡುಕಿ.</li><li>ನಿಮ್ಮ EPIC ಕಾರ್ಡ್ ಅಥವಾ ಅನುಮೋದಿತ ಫೋಟೋ ID (ಆಧಾರ್, ಪಾಸ್‌ಪೋರ್ಟ್ ಇತ್ಯಾದಿ) ತರಿ.</li><li>ನಕಲಿ ಮತದಾನವನ್ನು ತಡೆಯಲು ನಿಮ್ಮ ಬೆರಳಿಗೆ ಅಳಿಸಲಾಗದ ಶಾಯಿಯನ್ನು ಹಾಕಲಾಗುತ್ತದೆ.</li><li><strong>EVM</strong> ನಲ್ಲಿ ನಿಮ್ಮ ಅಭ್ಯರ್ಥಿಯ ಪಕ್ಕದಲ್ಲಿರುವ ಗುಂಡಿಯನ್ನು ಒತ್ತಿ.</li><li><strong>VVPAT</strong> (ಪೇಪರ್ ಟ್ರಯಲ್ ಸ್ಲಿಪ್) ನಲ್ಲಿ ನಿಮ್ಮ ಮತವನ್ನು ಪರಿಶೀಲಿಸಿ.</li></ul><div class="alert alert-caution">🚨 ಮತದಾನವು ಸಾಮಾನ್ಯವಾಗಿ ಬೆಳಿಗ್ಗೆ 7 ರಿಂದ ಸಂಜೆ 6 ರವರೆಗೆ ಇರುತ್ತದೆ. ಉದ್ದನೆಯ ಸರತಿ ಸಾಲುಗಳನ್ನು ತಪ್ಪಿಸಲು ಬೇಗನೆ ಬನ್ನಿ.</div>` },
        { num: 5, icon: '📊', title: 'ಎಣಿಕೆ ಮತ್ತು ಫಲಿತಾಂಶಗಳು', summary: 'EVM ಗಳನ್ನು ಒಂದೇ ಗೊತ್ತುಪಡಿಸಿದ ದಿನದಂದು ಎಣಿಸಲಾಗುತ್ತದೆ.',
          details: `<ul><li><strong>ಎಣಿಕೆಯ ದಿನ</strong> — ಎಣಿಕೆ ಕೇಂದ್ರಗಳಲ್ಲಿ ಎಲ್ಲಾ ಹಂತಗಳನ್ನು ಏಕಕಾಲದಲ್ಲಿ ಎಣಿಸಲಾಗುತ್ತದೆ.</li><li><strong>EVM ಎಣಿಕೆ</strong> — ಕಟ್ಟುನಿಟ್ಟಾದ ಮೇಲ್ವಿಚಾರಣೆಯಲ್ಲಿ ಎಲೆಕ್ಟ್ರಾನಿಕ್ ಯಂತ್ರಗಳ ಎಣಿಕೆ.</li><li><strong>VVPAT ಪರಿಶೀಲನೆ</strong> — ಯಾದೃಚ್ಛಿಕ VVPAT ಸ್ಲಿಪ್‌ಗಳನ್ನು EVM ಫಲಿತಾಂಶಗಳೊಂದಿಗೆ ಹೊಂದಿಸಲಾಗುತ್ತದೆ.</li><li><strong>ಫಲಿತಾಂಶಗಳು</strong> — ಅದೇ ದಿನ ಘೋಷಿಸಲಾಗುತ್ತದೆ; 272+ ಲೋಕಸಭಾ ಸ್ಥಾನಗಳನ್ನು ಹೊಂದಿರುವ ಪಕ್ಷ/ಮೈತ್ರಿ ಸರ್ಕಾರ ರಚಿಸುತ್ತದೆ.</li></ul>` },
        { num: 6, icon: '🏁', title: 'ಸರ್ಕಾರ ರಚನೆ', summary: 'ಬಹುಮತ ಹೊಂದಿರುವ ಪಕ್ಷ/ಮೈತ್ರಿ ಸರ್ಕಾರವನ್ನು ರಚಿಸುತ್ತದೆ.',
          details: `<ul><li><strong>ಬಹುಮತದ ಗುರುತು</strong> — 543 ಸದಸ್ಯರ ಲೋಕಸಭೆಯಲ್ಲಿ 272 ಸ್ಥಾನಗಳ ಅಗತ್ಯವಿದೆ.</li><li><strong>PM ಆಯ್ಕೆ</strong> — ಬಹುಮತ ಪಕ್ಷ/ಮೈತ್ರಿಯ ನಾಯಕ ಪ್ರಧಾನ ಮಂತ್ರಿಯಾಗುತ್ತಾರೆ.</li><li><strong>ಸಮ್ಮಿಶ್ರ ಸರ್ಕಾರ</strong> — ಯಾವುದೇ ಒಂದು ಪಕ್ಷಕ್ಕೆ ಬಹುಮತ ಸಿಗದಿದ್ದರೆ, ಮೈತ್ರಿಗಳನ್ನು ರಚಿಸಲಾಗುತ್ತದೆ.</li><li><strong>ಪ್ರಮಾಣ ವಚನ</strong> — ರಾಷ್ಟ್ರಪತಿಗಳಿಂದ PM ಮತ್ತು ಮಂತ್ರಿಮಂಡಲಕ್ಕೆ ಪ್ರಮಾಣ ವಚನ ಬೋಧನೆ.</li></ul>` },
      ],
      faq: [
        { q: 'EVM ಮತ್ತು VVPAT ಎಂದರೇನು?', a: 'ಎಲೆಕ್ಟ್ರಾನಿಕ್ ರೂಪದಲ್ಲಿ ಮತ ಚಲಾಯಿಸಲು EVM (ಎಲೆಕ್ಟ್ರಾನಿಕ್ ವೋಟಿಂಗ್ ಯಂತ್ರ) ಬಳಸಲಾಗುತ್ತದೆ. VVPAT (ವೋಟರ್ ವೆರಿಫೈಯಬಲ್ ಪೇಪರ್ ಆಡಿಟ್ ಟ್ರಯಲ್) ಪೇಪರ್ ಸ್ಲಿಪ್ ಅನ್ನು ಮುದ್ರಿಸುತ್ತದೆ ಇದರಿಂದ ನಿಮ್ಮ ಮತ ಸರಿಯಾಗಿ ದಾಖಲಾಗಿದೆಯೇ ಎಂದು ನೀವು ಪರಿಶೀಲಿಸಬಹುದು.' },
        { q: 'ಭಾರತವು ಏಕೆ ಹಲವಾರು ಹಂತಗಳಲ್ಲಿ ಮತ ಚಲಾಯಿಸುತ್ತದೆ?', a: 'ಬೃಹತ್ ಪ್ರಮಾಣದ ಕಾರಣ (900 ಮಿಲಿಯನ್‌ಗಿಂತಲೂ ಹೆಚ್ಚು ಮತದಾರರು), ದೇಶದಾದ್ಯಂತ ಭದ್ರತಾ ಪಡೆಗಳು ಮತ್ತು ECI ಅಧಿಕಾರಿಗಳನ್ನು ನಿಯೋಜಿಸಲು ಚುನಾವಣೆಗಳನ್ನು ಹಂತ ಹಂತವಾಗಿ ನಡೆಸಲಾಗುತ್ತದೆ.' },
        { q: 'ಮಾದರಿ ನೀತಿ ಸಂಹಿತೆ ಎಂದರೇನು?', a: 'ಚುನಾವಣೆಗಳ ಸಮಯದಲ್ಲಿ ಪಕ್ಷಗಳು ಮತ್ತು ಅಭ್ಯರ್ಥಿಗಳ ನಡವಳಿಕೆಯನ್ನು ನಿಯಂತ್ರಿಸುವ ECI ಹೊರಡಿಸಿದ ನಿಯಮಗಳ ಒಂದು ಸೆಟ್ — ದ್ವೇಷದ ಭಾಷಣವಿಲ್ಲ, ರಾಜಕೀಯ ಲಾಭಕ್ಕಾಗಿ ಸರ್ಕಾರಿ ಘೋಷಣೆಗಳಿಲ್ಲ, ಇತ್ಯಾದಿ.' },
        { q: 'ಅನಿವಾಸಿ ಭಾರತೀಯರು (NRI) ಭಾರತೀಯ ಚುನಾವಣೆಗಳಲ್ಲಿ ಮತ ಚಲಾಯಿಸಬಹುದೇ?', a: 'ಹೌದು, ಸಾಗರೋತ್ತರ ಮತದಾರರಾಗಿ ನೋಂದಾಯಿಸಿಕೊಂಡಿದ್ದರೆ NRI ಗಳು ಮತ ಚಲಾಯಿಸಬಹುದು, ಆದರೆ ಅವರು ಖುದ್ದಾಗಿ ಮತಗಟ್ಟೆಯಲ್ಲಿ ಹಾಜರಿರಬೇಕು. ಅಂಚೆ ಮತದಾನದ ಸೌಲಭ್ಯವನ್ನು ವಿಸ್ತರಿಸಲಾಗುತ್ತಿದೆ.' },
        { q: 'ವೋಟರ್ ಐಡಿಯಾಗಿ ನಾನು ಯಾವ ದಾಖಲೆಗಳನ್ನು ಬಳಸಬಹುದು?', a: 'EPIC ಕಾರ್ಡ್, ಆಧಾರ್, ಪಾಸ್‌ಪೋರ್ಟ್, ಡ್ರೈವಿಂಗ್ ಲೈಸೆನ್ಸ್, ಪ್ಯಾನ್ ಕಾರ್ಡ್ ಅಥವಾ ECI ಯಿಂದ ಅನುಮೋದಿಸಲಾದ ಯಾವುದೇ ಸರ್ಕಾರಿ ಫೋಟ ID.' },
      ],
      checklist: ['ಮತದಾರರ ಪಟ್ಟಿಯಲ್ಲಿ ನಿಮ್ಮ ಹೆಸರನ್ನು ಪರಿಶೀಲಿಸಿ (nvsp.in)', 'ನಿಮ್ಮ EPIC ಕಾರ್ಡ್ ಅಥವಾ ಅನುಮೋದಿತ ಫೋಟೋ ID ಸಿದ್ಧವಾಗಿಡಿ', 'ವೋಟರ್ ಹೆಲ್ಪ್‌ಲೈನ್ ಅಪ್ಲಿಕೇಶನ್‌ನಲ್ಲಿ ನಿಮ್ಮ ಮತಗಟ್ಟೆಯನ್ನು ಹುಡುಕಿ', 'myneta.info ನಲ್ಲಿ ಅಭ್ಯರ್ಥಿಗಳನ್ನು ಸಂಶೋಧಿಸಿ', 'ನಿಮ್ಮ ಕ್ಷೇತ್ರದ ಮತದಾನದ ಹಂತ ಮತ್ತು ದಿನಾಂಕವನ್ನು ಪರಿಶೀಲಿಸಿ', 'EVM ಬಳಸಿ ಮತ ಚಲಾಯಿಸಿ ಮತ್ತು VVPAT ನಲ್ಲಿ ಪರಿಶೀಲಿಸಿ', 'eciresults.nic.in ನಲ್ಲಿ ಫಲಿತಾಂಶಗಳನ್ನು ಪರಿಶೀಲಿಸಿ'],
    },
    ta: {
      timeline: [
        { phase: '6–12 மாதங்களுக்கு முன்', title: 'தேர்தலுக்கு முந்தைய காலம்', desc: 'அரசியல் கட்சிகள் தேர்தல் அறிக்கைகளை தயார் செய்கின்றன, கூட்டணிகளை உருவாக்குகின்றன, வேட்பாளர்களைத் தேர்ந்தெடுக்கின்றன.' },
        { phase: '2–3 மாதங்களுக்கு முன்', title: 'தேர்தல் அறிவிப்பு', desc: 'இந்திய தேர்தல் ஆணையம் (ECI) தேதிகளை அறிவிக்கிறது மற்றும் மாதிரி நடத்தை விதிகள் அமலுக்கு வருகின்றன.' },
        { phase: '1–2 மாதங்களுக்கு முன்', title: 'பிரச்சார காலம்', desc: 'தொகுதிகள் முழுவதும் பேரணிகள், வாகனப் பேரணிகள் மற்றும் ஊடகப் பிரச்சாரங்கள்.' },
        { phase: 'கடைசி தேதிக்கு முன்', title: 'வாக்காளர் பட்டியல் சரிபார்ப்பு', desc: 'nvsp.in இல் வாக்காளர் பட்டியலில் உங்கள் பெயரைச் சரிபார்க்கவும்.' },
        { phase: 'பல கட்டங்களாக', title: 'வாக்குப்பதிவு நாட்கள்', desc: 'இந்தியா EVM களைப் பயன்படுத்தி 4-6 வாரங்களில் பல கட்டங்களாக வாக்களிக்கிறது.' },
        { phase: 'இறுதி கட்டத்திற்குப் பிறகு', title: 'வாக்கு எண்ணிக்கை மற்றும் முடிவுகள்', desc: 'வாக்குகள் ஒரே நேரத்தில் எண்ணப்படுகின்றன. முடிவுகள் அதே நாளில் அறிவிக்கப்படும்.' },
      ],
      steps: [
        { num: 1, icon: '📝', title: 'வாக்காளர் பதிவு', summary: 'EPIC அட்டையுடன் வாக்காளர் பட்டியலில் உங்கள் பெயரைச் சேர்க்கவும்.',
          details: `<ul><li><strong>தகுதி:</strong> இந்திய குடிமகன், 18+ வயது, தொகுதியின் குடியிருப்பாளர்.</li><li><strong>எப்படி:</strong> nvsp.in இல் ஆன்லைனில் அல்லது Voter Helpline App (படிவம் 6) மூலம் விண்ணப்பிக்கவும்.</li><li><strong>EPIC அட்டை:</strong> புகைப்பட வாக்காளர் அடையாள அட்டை — உங்கள் முதன்மை வாக்காளர் அடையாள அட்டை.</li><li><strong>தேவையானவை:</strong> ஆதார், வயதுச் சான்று, பாஸ்போர்ட் அளவு புகைப்படம், முகவரிச் சான்று.</li></ul><div class="alert alert-important">⚠️ ஒவ்வொரு தேர்தலுக்கும் முன் வாக்காளர் பட்டியலைச் சரிபார்க்கவும் — திருத்தங்களின் போது பெயர்கள் நீக்கப்படலாம்.</div>` },
        { num: 2, icon: '🏛️', title: 'வேட்பாளர்கள் மற்றும் கட்சிகள்', summary: 'தேசிய மற்றும் மாநில கட்சி வேட்பாளர்களைப் பற்றி அறிந்து கொள்ளுங்கள்.',
          details: `<ul><li><strong>தேசிய கட்சிகள்</strong> — ECI ஆல் அங்கீகரிக்கப்பட்ட BJP, INC மற்றும் பிற.</li><li><strong>மாநில கட்சிகள்</strong> — AAP, TMC, DMK போன்ற மாநில அளவிலான கட்சிகள்.</li><li><strong>சுயேச்சை வேட்பாளர்கள்</strong> — வைப்புத் தொகையுடன் வேட்புமனு தாக்கல் செய்து போட்டியிடலாம்.</li><li><strong>பிரமாணப் பத்திரங்கள்</strong> — வேட்பாளர்கள் சொத்துக்கள், குற்ற வழக்குகள் மற்றும் கல்வியை அறிவிக்க வேண்டும்.</li></ul><div class="alert alert-tip">💡 வெளிப்படைத்தன்மைக்காக ECI இணையதளம் அல்லது MyNeta.info இல் வேட்பாளர் பிரமாணப் பத்திரங்களைச் சரிபார்க்கவும்.</div>` },
        { num: 3, icon: '📢', title: 'பிரச்சார காலம்', summary: 'MCC இன் கீழ் பேரணிகள், வாகனப் பேரணிகள் மற்றும் ஊடகப் பிரச்சாரங்கள்.',
          details: `<ul><li>🎤 <strong>பொதுக்கூட்டங்கள்</strong> — கட்சித் தலைவர்கள் உரையாற்றும் பெரிய கூட்டங்கள்.</li><li>🚗 <strong>வாகனப் பேரணிகள்</strong> — தொகுதிகள் வழியாக வேட்பாளர்களின் ஊர்வலம்.</li><li>📱 <strong>சமூக ஊடகங்கள்</strong> — பிரச்சாரம் மற்றும் செய்திகளுக்குப் பெரிதும் பயன்படுத்தப்படுகிறது.</li><li>📜 <strong>மாதிரி நடத்தை விதிகள்</strong> — ECI ஆல் அமல்படுத்தப்படும் பிரச்சாரத்திற்கான கடுமையான விதிகள்.</li></ul><div class="alert alert-warning">⚠️ ஒவ்வொரு கட்டத்திலும் வாக்குப்பதிவு நாளுக்கு 48 மணி நேரத்திற்கு முன் பிரச்சாரம் நிறுத்தப்பட வேண்டும்.</div>` },
        { num: 4, icon: '🗳️', title: 'உங்கள் வாக்கைப் பதிவு செய்தல்', summary: 'மின்னணு வாக்குப்பதிவு இயந்திரங்களை (EVMs) பயன்படுத்தி வாக்களிக்கவும்.',
          details: `<ul><li>Voter Helpline App அல்லது nvsp.in இல் உங்கள் வாக்குச்சாவடியைக் கண்டறியவும்.</li><li>உங்கள் EPIC அட்டை அல்லது அங்கீகரிக்கப்பட்ட புகைப்பட ID ஐ (ஆதார், பாஸ்போர்ட் போன்றவை) கொண்டு வாருங்கள்.</li><li>கள்ள ஓட்டுப் போடுவதைத் தடுக்க உங்கள் விரலில் அழியாத மை வைக்கப்படும்.</li><li><strong>EVM</strong> இல் உங்கள் வேட்பாளருக்குப் பக்கத்தில் உள்ள பொத்தானை அழுத்தவும்.</li><li><strong>VVPAT</strong> (காகித தணிக்கை சீட்டு) இல் உங்கள் வாக்கைச் சரிபார்க்கவும்.</li></ul><div class="alert alert-caution">🚨 வாக்குப்பதிவு பொதுவாக காலை 7 மணி முதல் மாலை 6 மணி வரை நடைபெறும். நீண்ட வரிசைகளைத் தவிர்க்க முன்கூட்டியே செல்லவும்.</div>` },
        { num: 5, icon: '📊', title: 'வாக்கு எண்ணிக்கை மற்றும் முடிவுகள்', summary: 'EVM கள் ஒரே நாளில் எண்ணப்படுகின்றன.',
          details: `<ul><li><strong>வாக்கு எண்ணிக்கை நாள்</strong> — அனைத்து கட்டங்களும் வாக்கு எண்ணிக்கை மையங்களில் ஒரே நேரத்தில் எண்ணப்படுகின்றன.</li><li><strong>EVM எண்ணிக்கை</strong> — கடுமையான கண்காணிப்பின் கீழ் மின்னணு இயந்திரங்கள் எண்ணப்படுகின்றன.</li><li><strong>VVPAT சரிபார்ப்பு</strong> — சீரற்ற VVPAT சீட்டுகள் EVM முடிவுகளுடன் ஒப்பிடப்படுகின்றன.</li><li><strong>முடிவுகள்</strong> — அதே நாளில் அறிவிக்கப்படும்; 272+ மக்களவை இடங்களைக் கொண்ட கட்சி/கூட்டணி அரசாங்கத்தை அமைக்கிறது.</li></ul>` },
        { num: 6, icon: '🏁', title: 'அரசாங்கம் அமைத்தல்', summary: 'பெரும்பான்மை பெற்ற கட்சி/கூட்டணி அரசாங்கத்தை அமைக்கிறது.',
          details: `<ul><li><strong>பெரும்பான்மை</strong> — 543 உறுப்பினர்களைக் கொண்ட மக்களவையில் 272 இடங்கள் தேவை.</li><li><strong>பிரதமர் தேர்வு</strong> — பெரும்பான்மை கட்சி/கூட்டணியின் தலைவர் பிரதமராகிறார்.</li><li><strong>கூட்டணி</strong> — எந்த ஒரு கட்சிக்கும் பெரும்பான்மை கிடைக்கவில்லை என்றால், கூட்டணிகள் உருவாக்கப்படுகின்றன.</li><li><strong>பதவியேற்பு</strong> — குடியரசுத் தலைவரால் பிரதமர் மற்றும் அமைச்சரவைக்கு பதவிப் பிரமாணம் செய்து வைக்கப்படுகிறது.</li></ul>` },
      ],
      faq: [
        { q: 'EVM மற்றும் VVPAT என்றால் என்ன?', a: 'EVM (மின்னணு வாக்குப்பதிவு இயந்திரம்) மின்னணு முறையில் வாக்களிக்கப் பயன்படுகிறது. VVPAT (வாக்காளர் சரிபார்க்கக்கூடிய காகித தணிக்கை முறை) ஒரு காகித சீட்டை அச்சிடுகிறது, இதன் மூலம் உங்கள் வாக்கு சரியாகப் பதிவாகியுள்ளதா என்பதை நீங்கள் சரிபார்க்கலாம்.' },
        { q: 'இந்தியா ஏன் பல கட்டங்களாக வாக்களிக்கிறது?', a: 'பாரிய அளவு (900 மில்லியனுக்கும் அதிகமான வாக்காளர்கள்) காரணமாக, பாதுகாப்புப் படையினர் மற்றும் ECI அதிகாரிகளை நாடு முழுவதும் பணியமர்த்த வசதியாக தேர்தல்கள் கட்டங்களாக நடத்தப்படுகின்றன.' },
        { q: 'மாதிரி நடத்தை விதிகள் என்றால் என்ன?', a: 'தேர்தலின் போது கட்சிகள் மற்றும் வேட்பாளர்களின் நடத்தையை ஒழுங்குபடுத்தும் ECI வெளியிட்ட விதிகள் — வெறுப்புப் பேச்சு கூடாது, அரசியல் ஆதாயத்திற்காக அரசு அறிவிப்புகள் கூடாது போன்றவை.' },
        { q: 'என்ஆர்ஐகள் (NRIs) இந்தியத் தேர்தல்களில் வாக்களிக்க முடியுமா?', a: 'ஆம், வெளிநாட்டு வாக்காளர்களாகப் பதிவு செய்திருந்தால் NRI கள் வாக்களிக்கலாம், ஆனால் அவர்கள் வாக்குச்சாவடிக்கு நேரில் வர வேண்டும். தபால் வாக்கு வசதி விரிவுபடுத்தப்பட்டு வருகிறது.' },
        { q: 'வாக்காளர் அடையாள அட்டையாக நான் என்ன ஆவணங்களைப் பயன்படுத்தலாம்?', a: 'EPIC அட்டை, ஆதார், பாஸ்போர்ட், ஓட்டுநர் உரிமம், பான் அட்டை அல்லது ECI ஆல் அங்கீகரிக்கப்பட்ட அரசு வழங்கிய புகைப்பட ID.' },
      ],
      checklist: ['வாக்காளர் பட்டியலில் உங்கள் பெயரைச் சரிபார்க்கவும் (nvsp.in)', 'உங்கள் EPIC அட்டை அல்லது அங்கீகரிக்கப்பட்ட புகைப்பட ID ஐ தயார் நிலையில் வைக்கவும்', 'Voter Helpline App இல் உங்கள் வாக்குச்சாவடியைக் கண்டறியவும்', 'myneta.info இல் வேட்பாளர்களைப் பற்றி ஆராயுங்கள்', 'உங்கள் தொகுதியின் வாக்குப்பதிவு கட்டம் மற்றும் தேதியைச் சரிபார்க்கவும்', 'EVM ஐப் பயன்படுத்தி வாக்களித்து VVPAT இல் சரிபார்க்கவும்', 'eciresults.nic.in இல் முடிவுகளைச் சரிபார்க்கவும்'],
    },
    te: {
      timeline: [
        { phase: '6–12 నెలల ముందు', title: 'ఎన్నికల ముందు', desc: 'రాజకీయ పార్టీలు మేనిఫెస్టోలను సిద్ధం చేస్తాయి, పొత్తులు కుదుర్చుకుంటాయి మరియు అభ్యర్థులను ఎంపిక చేస్తాయి.' },
        { phase: '2–3 నెలల ముందు', title: 'ఎన్నికల ప్రకటన', desc: 'భారత ఎన్నికల సంఘం (ECI) తేదీలను ప్రకటిస్తుంది మరియు మోడల్ కోడ్ ఆఫ్ కండక్ట్ అమల్లోకి వస్తుంది.' },
        { phase: '1–2 నెలల ముందు', title: 'ప్రచార సీజన్', desc: 'నియోజకవర్గాల వ్యాప్తంగా ర్యాలీలు, రోడ్‌షోలు మరియు మీడియా ప్రచారాలు.' },
        { phase: 'గడువుకు ముందు', title: 'ఓటరు జాబితా ధృవీకరణ', desc: 'nvsp.in లో ఓటరు జాబితాలో మీ పేరును తనిఖీ చేయండి.' },
        { phase: 'బహుళ దశల్లో', title: 'పోలింగ్ రోజులు', desc: 'భారతదేశం EVM లను ఉపయోగించి 4-6 వారాల్లో బహుళ దశల్లో ఓటు వేస్తుంది.' },
        { phase: 'చివరి దశ తర్వాత', title: 'లెక్కింపు రోజు మరియు ఫలితాలు', desc: 'ఓట్లు ఒకేసారి లెక్కించబడతాయి. ఫలితాలు అదే రోజు ప్రకటించబడతాయి.' },
      ],
      steps: [
        { num: 1, icon: '📝', title: 'ఓటరు నమోదు', summary: 'EPIC కార్డ్‌తో ఓటరు జాబితాలో మీ పేరును నమోదు చేసుకోండి.',
          details: `<ul><li><strong>అర్హత:</strong> భారతీయ పౌరుడు, 18+ వయస్సు, నియోజకవర్గ నివాసి.</li><li><strong>ఎలా:</strong> nvsp.in లో ఆన్‌లైన్‌లో లేదా ఓటర్ హెల్ప్‌లైన్ యాప్ (ఫారం 6) ద్వారా దరఖాస్తు చేసుకోండి.</li><li><strong>EPIC కార్డ్:</strong> ఎలక్టర్స్ ఫోటో ఐడెంటిటీ కార్డ్ — మీ ప్రాథమిక ఓటర్ ID.</li><li><strong>ఏమి కావాలి:</strong> ఆధార్, వయస్సు రుజువు, పాస్‌పోర్ట్ సైజు ఫోటో, చిరునామా రుజువు.</li></ul><div class="alert alert-important">⚠️ ప్రతి ఎన్నికల ముందు ఓటరు జాబితాను తనిఖీ చేయండి — సవరణల సమయంలో పేర్లు తొలగించబడవచ్చు.</div>` },
        { num: 2, icon: '🏛️', title: 'అభ్యర్థులు మరియు పార్టీలు', summary: 'జాతీయ మరియు ప్రాంతీయ పార్టీ అభ్యర్థుల గురించి తెలుసుకోండి.',
          details: `<ul><li><strong>జాతీయ పార్టీలు</strong> — ECI ద్వారా గుర్తించబడిన BJP, INC మరియు ఇతర పార్టీలు.</li><li><strong>ప్రాంతీయ పార్టీలు</strong> — AAP, TMC, DMK వంటి రాష్ట్ర స్థాయి పార్టీలు.</li><li><strong>స్వతంత్ర అభ్యర్థులు</strong> — డిపాజిట్‌తో నామినేషన్ దాఖలు చేయడం ద్వారా పోటీ చేయవచ్చు.</li><li><strong>అఫిడవిట్‌లు</strong> — అభ్యర్థులు ఆస్తులు, క్రిమినల్ కేసులు మరియు విద్యను ప్రకటించాలి.</li></ul><div class="alert alert-tip">💡 పారదర్శకత కోసం ECI వెబ్‌సైట్ లేదా MyNeta.info లో అభ్యర్థి అఫిడవిట్‌లను తనిఖీ చేయండి.</div>` },
        { num: 3, icon: '📢', title: 'ప్రచార సీజన్', summary: 'MCC కింద ర్యాలీలు, రోడ్‌షోలు మరియు మీడియా ప్రచారాలు.',
          details: `<ul><li>🎤 <strong>బహిరంగ సభలు</strong> — పార్టీ నాయకులు ప్రసంగించే పెద్ద సమావేశాలు.</li><li>🚗 <strong>రోడ్‌షోలు</strong> — నియోజకవర్గాల ద్వారా అభ్యర్థుల ఊరేగింపు.</li><li>📱 <strong>సోషల్ మీడియా</strong> — ప్రచారం మరియు సందేశాల కోసం ఎక్కువగా ఉపయోగించబడుతుంది.</li><li>📜 <strong>మోడల్ కోడ్ ఆఫ్ కండక్ట్</strong> — ECI ద్వారా అమలు చేయబడే ప్రచారంపై కఠినమైన నియమాలు.</li></ul><div class="alert alert-warning">⚠️ ప్రతి దశలో పోలింగ్ రోజుకు 48 గంటల ముందు ప్రచారం ఆగిపోవాలి.</div>` },
        { num: 4, icon: '🗳️', title: 'మీ ఓటు వేయడం', summary: 'ఎలక్ట్రానిక్ ఓటింగ్ యంత్రాలను (EVMs) ఉపయోగించి ఓటు వేయండి.',
          details: `<ul><li>ఓటర్ హెల్ప్‌లైన్ యాప్ లేదా nvsp.in లో మీ పోలింగ్ బూత్‌ను కనుగొనండి.</li><li>మీ EPIC కార్డ్ లేదా ఆమోదించబడిన ఫోటో ID (ఆధార్, పాస్‌పోర్ట్ మొదలైనవి) తీసుకురండి.</li><li>నకిలీ ఓటింగ్‌ను నిరోధించడానికి మీ వేలికి చెరగని సిరా వేయబడుతుంది.</li><li><strong>EVM</strong> లో మీ అభ్యర్థి పక్కన ఉన్న బటన్‌ను నొక్కండి.</li><li><strong>VVPAT</strong> (పేపర్ ఆడిట్ స్లిప్) లో మీ ఓటును ధృవీకరించుకోండి.</li></ul><div class="alert alert-caution">🚨 పోలింగ్ సాధారణంగా ఉదయం 7 నుండి సాయంత్రం 6 వరకు ఉంటుంది. రద్దీని నివారించడానికి త్వరగా రండి.</div>` },
        { num: 5, icon: '📊', title: 'లెక్కింపు మరియు ఫలితాలు', summary: 'EVM లు ఒకే రోజున లెక్కించబడతాయి.',
          details: `<ul><li><strong>లెక్కింపు రోజు</strong> — అన్ని దశలు లెక్కింపు కేంద్రాల్లో ఏకకాలంలో లెక్కించబడతాయి.</li><li><strong>EVM లెక్కింపు</strong> — కఠినమైన పర్యవేక్షణలో ఎలక్ట్రానిక్ యంత్రాల లెక్కింపు.</li><li><strong>VVPAT ధృవీకరణ</strong> — యాదృచ్ఛిక VVPAT స్లిప్‌లు EVM ఫలితాలతో సరిపోల్చబడతాయి.</li><li><strong>ఫలితాలు</strong> — అదే రోజు ప్రకటించబడతాయి; 272+ లోక్‌సభ స్థానాలు ఉన్న పార్టీ/కూటమి ప్రభుత్వాన్ని ఏర్పాటు చేస్తుంది.</li></ul>` },
        { num: 6, icon: '🏁', title: 'ప్రభుత్వ ఏర్పాటు', summary: 'మెజారిటీ ఉన్న పార్టీ/కూటమి ప్రభుత్వాన్ని ఏర్పాటు చేస్తుంది.',
          details: `<ul><li><strong>మెజారిటీ మార్క్</strong> — 543 మంది సభ్యుల లోక్‌సభలో 272 స్థానాలు అవసరం.</li><li><strong>PM ఎంపిక</strong> — మెజారిటీ పార్టీ/కూటమి నాయకుడు ప్రధాన మంత్రి అవుతాడు.</li><li><strong>సంకీర్ణం</strong> — ఏ ఒక్క పార్టీకి మెజారిటీ రాకపోతే, పొత్తులు కుదుర్చుకుంటారు.</li><li><strong>ప్రమాణ స్వీకారం</strong> — రాష్ట్రపతిచే PM మరియు మంత్రి మండలికి ప్రమాణ స్వీకారం.</li></ul>` },
      ],
      faq: [
        { q: 'EVM మరియు VVPAT అంటే ఏమిటి?', a: 'ఎలక్ట్రానిక్ రూపంలో ఓటు వేయడానికి EVM (ఎలక్ట్రానిక్ ఓటింగ్ మెషిన్) ఉపయోగించబడుతుంది. VVPAT (ఓటర్ వెరిఫైయబుల్ పేపర్ ఆడిట్ ట్రైల్) పేపర్ స్లిప్‌ను ప్రింట్ చేస్తుంది కాబట్టి మీ ఓటు సరిగ్గా నమోదు చేయబడిందో లేదో మీరు ధృవీకరించవచ్చు.' },
        { q: 'భారతదేశం ఎందుకు బహుళ దశల్లో ఓటు వేస్తుంది?', a: 'భారీ స్థాయి (900M+ ఓటర్లు) కారణంగా, దేశవ్యాప్తంగా భద్రతా దళాలు మరియు ECI అధికారులను మోహరించడానికి వీలుగా ఎన్నికలు దశలవారీగా నిర్వహించబడతాయి.' },
        { q: 'మోడల్ కోడ్ ఆఫ్ కండక్ట్ అంటే ఏమిటి?', a: 'ఎన్నికల సమయంలో పార్టీలు మరియు అభ్యర్థుల ప్రవర్తనను నియంత్రించే ECI జారీ చేసిన నియమాల సమితి — ద్వేషపూరిత ప్రసంగాలు లేవు, రాజకీయ ప్రయోజనం కోసం ప్రభుత్వ ప్రకటనలు లేవు మొదలైనవి.' },
        { q: 'NRI లు భారతీయ ఎన్నికలలో ఓటు వేయవచ్చా?', a: 'అవును, ఓవర్సీస్ ఓటర్లుగా నమోదు చేసుకుంటే NRI లు ఓటు వేయవచ్చు, కానీ వారు పోలింగ్ బూత్‌లో వ్యక్తిగతంగా హాజరు కావాలి. పోస్టల్ బ్యాలెట్ సౌకర్యం విస్తరించబడుతోంది.' },
        { q: 'ఓటర్ ID గా నేను ఏ పత్రాలను ఉపయోగించగలను?', a: 'EPIC కార్డ్, ఆధార్, పాస్‌పోర్ట్, డ్రైవింగ్ లైసెన్స్, పాన్ కార్డ్ లేదా ECI ఆమోదించిన ఏదైనా ప్రభుత్వ ఫోటో ID.' },
      ],
      checklist: ['ఓటరు జాబితాలో మీ పేరును ధృవీకరించండి (nvsp.in)', 'మీ EPIC కార్డ్ లేదా ఆమోదించబడిన ఫోటో ID సిద్ధంగా ఉంచుకోండి', 'ఓటర్ హెల్ప్‌లైన్ యాప్‌లో మీ పోలింగ్ బూత్‌ను కనుగొనండి', 'myneta.info లో అభ్యర్థులను పరిశోధించండి', 'మీ నియోజకవర్గం యొక్క పోలింగ్ దశ మరియు తేదీని తనిఖీ చేయండి', 'EVM ఉపయోగించి ఓటు వేయండి మరియు VVPAT లో ధృవీకరించండి', 'eciresults.nic.in లో ఫలితాలను తనిఖీ చేయండి'],
    },
  },
  ca: {
    fr: {
      timeline: [
        { phase: 'Jusqu\'à 4 ans', title: 'Mandat Parlementaire', desc: 'Dates d\'élection fixes (3e lundi d\'octobre), mais le PM peut déclencher plus tôt.' },
        { phase: '~50 Jours Avant', title: 'Déclenchement', desc: 'Le Gouverneur général dissout le Parlement sur avis du PM. Période de bref commence.' },
        { phase: 'Période de Bref', title: 'Campagne Électorale', desc: 'Campagne officielle avec débats des chefs et démarchage dans les circonscriptions.' },
        { phase: '6e Jour Avant', title: 'Date Limite d\'Inscription', desc: 'Dernier jour pour s\'inscrire. Inscription possible au bureau de vote le jour J.' },
        { phase: '4 Jours Avant', title: 'Vote par Anticipation', desc: 'Votez par anticipation dans les bureaux de vote anticipé pendant 4 jours.' },
        { phase: 'Lundi Désigné', title: 'Jour d\'Élection', desc: 'Les bureaux de vote ouvrent dans les 338 circonscriptions fédérales.' },
        { phase: 'Jours Suivants', title: 'Résultats et Gouvernement', desc: 'Dépouillement des votes. Le parti avec le plus de sièges forme le gouvernement.' },
      ],
      steps: [
        { num: 1, icon: '📝', title: 'Inscription des Électeurs', summary: 'Inscrivez-vous auprès d\'Élections Canada ou aux urnes.',
          details: `<ul><li><strong>Admissibilité :</strong> Citoyen canadien, 18 ans et plus le jour de l'élection.</li><li><strong>Comment :</strong> En ligne sur elections.ca, par la poste ou à votre bureau de vote le jour de l'élection.</li><li><strong>Ce dont vous avez besoin :</strong> Pièce d'identité avec photo émise par le gouvernement ou deux pièces d'identité avec nom et adresse.</li></ul><div class="alert alert-important">⚠️ Le Canada permet l'inscription le jour même aux urnes — apportez une pièce d'identité valide !</div>` },
        { num: 2, icon: '🏛️', title: 'Partis et Candidats', summary: 'Faites des recherches sur les partis et le candidat de votre circonscription.',
          details: `<ul><li><strong>Principaux Partis :</strong> Libéral, Conservateur, NPD, Bloc Québécois, Vert.</li><li><strong>Circonscriptions :</strong> Le Canada compte 338 circonscriptions électorales, chacune élisant un député.</li><li><strong>Système Majoritaire Uninominal :</strong> Le candidat avec le plus de votes remporte la circonscription.</li><li><strong>Chefs de Parti :</strong> Sélectionnés par des courses à la direction internes.</li></ul><div class="alert alert-tip">💡 Visitez elections.ca pour voir les candidats confirmés dans votre circonscription.</div>` },
        { num: 3, icon: '📢', title: 'Période de Campagne', summary: 'Débats, démarchage et couverture médiatique pendant la période électorale.',
          details: `<ul><li>📺 <strong>Débats des Chefs</strong> — Débats officiels en anglais et en français organisés par la Commission des débats des chefs.</li><li>🚪 <strong>Démarchage</strong> — Les candidats locaux et les bénévoles font du porte-à-porte.</li><li>📱 <strong>Campagnes Numériques</strong> — Médias sociaux et publicité en ligne.</li><li>📜 <strong>Limites de Dépenses</strong> — Élections Canada fixe des limites strictes pour les partis et les candidats.</li></ul>` },
        { num: 4, icon: '🗳️', title: 'Voter', summary: 'Votez par anticipation, le jour de l\'élection ou par la poste.',
          details: `<ul><li>Montrez votre pièce d'identité au bureau de vote.</li><li>Recevez un bulletin de vote en papier et marquez un <strong>X</strong> à côté de votre candidat.</li><li>Pliez et remettez le bulletin au scrutateur.</li></ul><h4 style="margin:1rem 0 0.5rem;color:#e2e8f0">Vote par Anticipation</h4><ul><li>Disponible le vendredi, samedi, dimanche et lundi — 10 jours avant le jour de l'élection.</li></ul><h4 style="margin:1rem 0 0.5rem;color:#e2e8f0">Par la Poste (Bulletin Spécial)</h4><ul><li>Faites une demande auprès d'Élections Canada. Disponible pour tous les électeurs inscrits.</li></ul><div class="alert alert-caution">🚨 Les bulletins spéciaux doivent être reçus par Élections Canada avant la fermeture des bureaux de vote le jour de l'élection.</div>` },
        { num: 5, icon: '📊', title: 'Dépouillement et Résultats', summary: 'Bulletins en papier comptés à la main le soir de l\'élection.',
          details: `<ul><li><strong>Comptage Manuel</strong> — Tous les bulletins sont comptés à la main dans chaque bureau de vote.</li><li><strong>Résultats</strong> — Résultats non officiels disponibles le soir de l'élection.</li><li><strong>170 Sièges</strong> — Un parti a besoin de 170 des 338 sièges pour être majoritaire.</li><li><strong>Résultats Officiels</strong> — Validés par les directeurs de scrutin dans chaque circonscription.</li></ul>` },
        { num: 6, icon: '🏁', title: 'Formation du Gouvernement', summary: 'Le parti avec le plus de sièges forme le gouvernement.',
          details: `<ul><li><strong>Gouvernement Majoritaire</strong> — 170+ sièges; peut gouverner sans autres partis.</li><li><strong>Gouvernement Minoritaire</strong> — Le parti le plus important gouverne avec le soutien d'autres partis.</li><li><strong>Nomination du PM</strong> — Le Gouverneur général demande au chef de former le gouvernement.</li><li><strong>Cabinet</strong> — Le PM choisit les ministres parmi les députés et sénateurs élus.</li></ul>` },
      ],
      faq: [
        { q: 'Puis-je m\'inscrire et voter le même jour?', a: 'Oui! Le Canada permet l\'inscription le jour même. Apportez une pièce d\'identité avec photo ou deux pièces d\'identité montrant votre nom et adresse.' },
        { q: 'Qu\'est-ce qu\'une circonscription?', a: 'Une circonscription (district électoral) est une zone géographique qui élit un député. Il y a 338 circonscriptions au Canada.' },
        { q: 'Y a-t-il des élections provinciales séparées?', a: 'Oui, chaque province et territoire tient ses propres élections pour sa législature, séparément des élections fédérales.' },
        { q: 'Puis-je voter depuis l\'étranger?', a: 'Oui, les citoyens canadiens vivant à l\'étranger peuvent voter par bulletin spécial via Élections Canada.' },
      ],
      checklist: ['Vérifier votre inscription sur elections.ca', 'Préparer une pièce d\'identité acceptée', 'Trouver votre bureau de vote', 'Rechercher les candidats de votre circonscription', 'Noter les dates de vote anticipé et du jour d\'élection', 'Déposer votre bulletin!', 'Suivre les résultats sur elections.ca'],
    },
  },
  gb: {
    cy: {
      timeline: [
        { phase: 'Hyd at 5 Mlynedd', title: 'Tymor Seneddol', desc: 'Gall y Senedd eistedd am hyd at 5 mlynedd cyn bod rhaid galw etholiad.' },
        { phase: '~6 Wythnos Cyn', title: 'Galw Etholiad', desc: 'Mae\'r PM yn gofyn am ddiddymiad y Senedd. Mae\'r cyfnod ymgyrchu\'n dechrau.' },
        { phase: '5 Wythnos Cyn', title: 'Tymor Ymgyrchu', desc: 'Maniffestos pleidiau, dadleuon, canfasio ar draws etholaethau.' },
        { phase: '12 Diwrnod Gwaith Cyn', title: 'Dyddiad Cau Cofrestru', desc: 'Diwrnod olaf i gofrestru i bleidleisio yn yr etholiad hwn.' },
        { phase: '11 Diwrnod Gwaith Cyn', title: 'Dyddiad Cau Pleidlais Bost', desc: 'Diwrnod olaf i wneud cais am bleidlais bost.' },
        { phase: 'Dydd Iau Dynodedig', title: 'Diwrnod Pleidleisio', desc: 'Gorsafoedd pleidleisio ar agor 7 AM – 10 PM ar draws 650 etholaeth.' },
        { phase: 'Y Diwrnod Wedyn', title: 'Canlyniadau a Llywodraeth', desc: 'Cyfrif dros nos. PM fel arfer wedi\'i gadarnhau erbyn y bore.' },
      ],
      steps: [
        { num: 1, icon: '📝', title: 'Cofrestru Etholiadol', summary: 'Cofrestrwch ar gov.uk — mae\'n cymryd 5 munud.',
          details: `<ul><li><strong>Cymhwysedd:</strong> Dinasyddion y DU/Gweriniaeth Iwerddon/y Gymanwlad cymwys, 18+ ar ddiwrnod pleidleisio.</li><li><strong>Sut:</strong> Cofrestrwch ar-lein ar gov.uk/register-to-vote.</li><li><strong>Beth sydd ei angen:</strong> Rhif Yswiriant Gwladol a dyddiad geni.</li><li><strong>Dyddiad Cau:</strong> 12 diwrnod gwaith cyn y diwrnod pleidleisio.</li></ul><div class="alert alert-important">⚠️ Rhaid i chi gofrestru'n unigol — nid yw bod ar y bil treth gyngor yn eich cofrestru'n awtomatig.</div>` },
        { num: 2, icon: '🏛️', title: 'Pleidiau ac Ymgeiswyr', summary: 'Deallwch y prif bleidiau a\'ch ymgeiswyr lleol.',
          details: `<ul><li><strong>Prif Bleidiau:</strong> Ceidwadwyr, Llafur, Democratiaid Rhyddfrydol, SNP, Plaid Cymru, Gwyrdd.</li><li><strong>Etholaethau:</strong> Mae'r DU wedi'i rhannu'n 650 o etholaethau, pob un yn ethol un AS.</li><li><strong>System FPTP:</strong> Yr ymgeisydd gyda'r mwyaf o bleidleisiau sy'n ennill.</li><li><strong>Maniffestos:</strong> Mae pob plaid yn cyhoeddi maniffesto sy'n amlinellu eu polisïau.</li></ul><div class="alert alert-tip">💡 Defnyddiwch TheyWorkForYou.com i wirio record bleidleisio eich AS presennol.</div>` },
        { num: 3, icon: '📢', title: 'Cyfnod Ymgyrchu', summary: 'Dadleuon, maniffestos, a chanfasio yn yr etholaethau.',
          details: `<ul><li>📺 <strong>Dadleuon Arweinwyr</strong> — Dadleuon ar y teledu rhwng arweinwyr pleidiau ar BBC/ITV.</li><li>📜 <strong>Maniffestos</strong> — Addewidion a chynlluniau polisi wedi'u cyhoeddi gan bob plaid.</li><li>🚪 <strong>Canfasio</strong> — Ymgeiswyr lleol yn curo drysau mewn etholaethau.</li><li>📰 <strong>Sylw yn y Cyfryngau</strong> — Wedi'i reoleiddio gan Ofcom ar gyfer cydbwysedd a thegwch.</li></ul><div class="alert alert-warning">⚠️ Mae rheolau darlledu yn gofyn am sylw cytbwys — yn wahanol i lawer o wledydd eraill.</div>` },
        { num: 4, icon: '🗳️', title: 'Bwrw Eich Pleidlais', summary: 'Pleidleisiwch yn eich gorsaf bleidleisio leol gyda phapur pleidleisio.',
          details: `<ul><li>Mae gorsafoedd pleidleisio ar agor <strong>7 AM – 10 PM</strong> ar ddiwrnod pleidleisio (dydd Iau bob amser).</li><li>Ewch i'ch gorsaf bleidleisio a glustnodwyd (wedi'i rhestru ar eich cerdyn pleidleisio).</li><li>Rhowch eich enw a chyfeiriad — <strong>mae angen llun ID</strong> ers 2023.</li><li>Rhowch <strong>X</strong> wrth ymyl eich ymgeisydd dewisol gyda phensil.</li><li>Plygwch a rhowch eich pleidlais yn y blwch pleidleisio.</li></ul><h4 style="margin:1rem 0 0.5rem;color:#e2e8f0">Pleidleisio drwy'r Post</h4><ul><li>Gwnewch gais o leiaf 11 diwrnod gwaith cyn yr etholiad.</li><li>Cwblhewch a dychwelwch cyn y diwrnod pleidleisio.</li></ul><div class="alert alert-caution">🚨 Rydych bellach angen llun ID i bleidleisio'n bersonol — gwiriwch ffurfiau derbyniol yn electoralcommission.org.uk.</div>` },
        { num: 5, icon: '📊', title: 'Cyfrif a Chanlyniadau', summary: 'Cyfrif dros nos gyda chanlyniadau erbyn y bore.',
          details: `<ul><li><strong>Noson Gyfrif</strong> — Cyfrif yn dechrau am 10 PM pan fydd gorsafoedd yn cau.</li><li><strong>Canlyniadau Etholaethol</strong> — Wedi'u datgan yn unigol drwy'r nos.</li><li><strong>Polau Ymadael</strong> — BBC/ITV/Sky yn cyhoeddi pôl ymadael ar y cyd am 10 PM.</li><li><strong>326 Sedd</strong> — Mae angen 326 o 650 sedd ar blaid am fwyafrif.</li></ul>` },
        { num: 6, icon: '🏁', title: 'Ffurfio Llywodraeth', summary: 'Arweinydd y blaid fwyafrifol sy\'n dod yn Brif Weinidog.',
          details: `<ul><li><strong>Llywodraeth Fwyafrifol</strong> — Plaid gyda 326+ o seddi yn ffurfio llywodraeth.</li><li><strong>Senedd Grog</strong> — Dim mwyafrif → clymblaid neu drafodaethau llywodraeth leiafrifol.</li><li><strong>Penodiad y PM</strong> — Mae'r Brenin yn gwahodd yr arweinydd i ffurfio llywodraeth.</li><li><strong>Cabinet</strong> — PM yn penodi gweinidogion o blith ASau eu plaid.</li></ul>` },
      ],
      faq: [
        { q: 'Oes angen llun ID i bleidleisio?', a: 'Oes, ers 2023 mae angen ffurf dderbyniol o ID llun i bleidleisio\'n bersonol yn Lloegr. Os nad oes gennych un, gallwch wneud cais am Dystysgrif Awdurdod Pleidleisiwr am ddim.' },
        { q: 'Beth yw Cyntaf i\'r Felin (FPTP)?', a: 'Y ymgeisydd gyda\'r mwyaf o bleidleisiau ym mhob etholaeth sy\'n ennill y sedd. Nid oes angen canran lleiaf.' },
        { q: 'A allaf bleidleisio os ydw i\'n ddinesydd y Gymanwlad?', a: 'Gallwch, gall dinasyddion cymwys y Gymanwlad sy\'n byw yn y DU gofrestru a phleidleisio ym mhob etholiad y DU.' },
        { q: 'Beth yw senedd grog?', a: 'Pan na fydd unrhyw blaid yn ennill 326+ sedd. Gall y blaid fwyaf geisio ffurfio clymblaid neu lywodraethu fel lleiafrif.' },
      ],
      checklist: ['Cofrestru yn gov.uk/register-to-vote', 'Gwiriwch fod gennych ID llun derbyniol', 'Dewch o hyd i\'ch gorsaf bleidleisio', 'Darllenwch faniffestos y pleidiau', 'Nodwch ddyddiad y diwrnod pleidleisio (bob amser dydd Iau)', 'Pleidleisiwch 7 AM – 10 PM ar ddiwrnod pleidleisio', 'Dilynwch y canlyniadau dros nos ar BBC/ITV'],
    },
  },
  de: {
    de: {
      timeline: [
        { phase: 'Alle 4 Jahre', title: 'Legislaturperiode', desc: 'Der Bundestag wird für 4 Jahre gewählt.' },
        { phase: '~3 Monate Vorher', title: 'Wahlkampf', desc: 'Parteien veröffentlichen Programme, halten Kundgebungen ab und debattieren im TV.' },
        { phase: '6 Wochen Vorher', title: 'Briefwahl Möglich', desc: 'Beantragen Sie die Briefwahl bei Ihrem örtlichen Wahlamt.' },
        { phase: '42. Tag Vorher', title: 'Nominierungsfrist', desc: 'Parteien stellen Kandidatenlisten für Wahlkreise und Landeslisten auf.' },
        { phase: 'Bestimmter Sonntag', title: 'Wahltag', desc: 'Wahllokale geöffnet 8–18 Uhr in allen 299 Wahlkreisen.' },
        { phase: 'Wochen Danach', title: 'Koalition und Regierung', desc: 'Parteien verhandeln Koalitionen. Kanzler/in wird vom Bundestag gewählt.' },
      ],
      steps: [
        { num: 1, icon: '📝', title: 'Wählerregistrierung', summary: 'Automatische Registrierung für die meisten — prüfen Sie einfach Ihre Benachrichtigung.',
          details: `<ul><li><strong>Wer darf wählen?</strong> Deutsche Staatsbürger, 18+, mit Wohnsitz in Deutschland.</li><li><strong>Automatisch:</strong> Wenn Sie bei Ihrem Einwohnermeldeamt gemeldet sind, stehen Sie automatisch im Wählerverzeichnis.</li><li><strong>Benachrichtigung:</strong> Sie erhalten ca. 4 Wochen vorher eine Wahlbenachrichtigung per Post.</li><li><strong>Im Ausland:</strong> Deutsche im Ausland müssen sich in das Wählerverzeichnis eintragen lassen.</li></ul><div class="alert alert-important">⚠️ Wenn Sie keine Wahlbenachrichtigung erhalten, wenden Sie sich sofort an Ihr örtliches Wahlamt.</div>` },
        { num: 2, icon: '🏛️', title: 'Parteien & das Zwei-Stimmen-System', summary: 'Sie haben ZWEI Stimmen — Erststimme und Zweitstimme.',
          details: `<ul><li><strong>Große Parteien:</strong> SPD, CDU/CSU, Grüne, FDP, AfD, Die Linke, BSW.</li><li><strong>Erststimme:</strong> Für einen Direktkandidaten in Ihrem Wahlkreis (299 Sitze).</li><li><strong>Zweitstimme:</strong> Für eine Partei — bestimmt die proportionale Zusammensetzung des Bundestages.</li><li><strong>5%-Hürde:</strong> Parteien müssen mindestens 5% der Zweitstimmen oder 3 Direktmandate gewinnen, um in den Bundestag einzuziehen.</li></ul><div class="alert alert-tip">💡 Die Zweitstimme gilt oft als die wichtigere Stimme, da sie die proportionale Sitzverteilung im Parlament bestimmt.</div>` },
        { num: 3, icon: '📢', title: 'Wahlkampf', summary: 'TV-Debatten, Parteiprogramme und Straßenwahlkampf.',
          details: `<ul><li>📺 <strong>TV-Duell / Triell</strong> — Debatten der Kanzlerkandidaten im öffentlich-rechtlichen Fernsehen.</li><li>📜 <strong>Wahlprogramm</strong> — Jede Partei veröffentlicht ein detailliertes Programm.</li><li>🗣️ <strong>Straßenwahlkampf</strong> — Infostände in Innenstädten und auf Marktplätzen.</li><li>📊 <strong>Sonntagsfrage</strong> — Wöchentliche Umfragen zur Parteipräferenz.</li></ul>` },
        { num: 4, icon: '🗳️', title: 'Stimmabgabe', summary: 'Wählen Sie am Sonntag persönlich oder per Briefwahl.',
          details: `<ul><li>Bringen Sie Ihre Wahlbenachrichtigung und einen Ausweis zu Ihrem zugewiesenen Wahllokal mit.</li><li>Sie erhalten einen Stimmzettel mit <strong>zwei Spalten</strong>.</li><li><strong>Linke Spalte (Erststimme):</strong> Machen Sie ein X für Ihren Wahlkreiskandidaten.</li><li><strong>Rechte Spalte (Zweitstimme):</strong> Machen Sie ein X für Ihre bevorzugte Partei.</li><li>Falten Sie den Zettel und werfen Sie ihn in die Wahlurne.</li></ul><h4 style="margin:1rem 0 0.5rem;color:#e2e8f0">Briefwahl</h4><ul><li>Beantragen Sie diese online oder indem Sie das Formular auf Ihrer Wahlbenachrichtigung zurücksenden.</li><li>Füllen Sie sie zu Hause aus und senden Sie sie so zurück, dass sie vor 18 Uhr am Wahltag ankommt.</li></ul><div class="alert alert-caution">🚨 Wahlen finden in Deutschland immer an einem Sonntag statt. Briefwahlunterlagen müssen bis 18 Uhr am Wahltag eingehen.</div>` },
        { num: 5, icon: '📊', title: 'Auszählung & Ergebnisse', summary: 'Die Zweitstimme bestimmt die proportionale Sitzverteilung.',
          details: `<ul><li><strong>18:00 Prognose</strong> — Erste Prognosen bei Schließung der Wahllokale auf Basis von Nachwahlbefragungen.</li><li><strong>Hochrechnungen</strong> — Aktualisierte Hochrechnungen im Laufe des Abends.</li><li><strong>Sitzverteilung</strong> — Die Zweitstimme bestimmt die proportionale Sitzverteilung.</li><li><strong>Überhangmandate</strong> — Zusätzliche Sitze, wenn eine Partei mehr Wahlkreise gewinnt, als ihr proportional zustehen.</li></ul>` },
        { num: 6, icon: '🏁', title: 'Koalition & Regierung', summary: 'Parteien verhandeln, um eine Koalitionsmehrheit zu bilden.',
          details: `<ul><li><strong>Koalitionsverhandlungen</strong> — Können Wochen bis Monate nach der Wahl dauern.</li><li><strong>Koalitionsvertrag</strong> — Die Koalitionspartner unterzeichnen eine formelle Vereinbarung.</li><li><strong>Kanzlerwahl</strong> — Der Bundestag wählt den Bundeskanzler / die Bundeskanzlerin.</li><li><strong>Kabinett</strong> — Minister werden vom Kanzler vorgeschlagen und vom Präsidenten ernannt.</li></ul>` },
      ],
      faq: [
        { q: 'Was ist der Unterschied zwischen Erststimme und Zweitstimme?', a: 'Die Erststimme wählt einen Direktkandidaten im Wahlkreis. Die Zweitstimme ist für eine Partei und bestimmt die proportionale Zusammensetzung des Bundestags. Die Zweitstimme gilt als wichtiger.' },
        { q: 'Was ist die 5%-Hürde?', a: 'Eine Partei muss mindestens 5% aller Zweitstimmen erhalten (oder 3 Direktmandate gewinnen), um in den Bundestag einzuziehen. Dies verhindert extreme Zersplitterung.' },
        { q: 'Warum finden Wahlen am Sonntag statt?', a: 'Um eine maximale Wahlbeteiligung zu gewährleisten, werden Wahlen an einem Tag abgehalten, an dem die meisten Menschen nicht arbeiten.' },
        { q: 'Wie funktionieren Koalitionsverhandlungen?', a: 'Nach der Wahl verhandeln die Parteien eine Koalition mit Bundestagsmehrheit. Sie einigen sich auf einen Koalitionsvertrag und wählen den Kanzler.' },
      ],
      checklist: ['Prüfen Sie, ob Ihre Wahlbenachrichtigung angekommen ist', 'Entscheiden: Vor Ort wählen oder Briefwahl beantragen', 'Wahlprogramme der Parteien studieren', 'Das Zwei-Stimmen-System verstehen (Erst- & Zweitstimme)', 'Ausweis und Wahlbenachrichtigung zum Wahllokal mitbringen', 'Beide Stimmen am Sonntag abgeben (8–18 Uhr)', 'Ergebnisse auf tagesschau.de verfolgen'],
    },
  },
};
